### ISSUE TITLE
`pnpm` install fail

### ISSUE THREAD

**Issue by zcf0508** [garvae/eslint-plugin-comments#1]
```shell
> pnpm install @garvae/eslint-plugin-comments --save-dev

Packages: +1
+
node_modules/.pnpm/@garvae+eslint-plugin-comments@1.0.5_eslint@8.42.0/node_modules/@garvae/eslint-plugin-comments: Running postinstall script...
Progress: resolved 700, reused 679, downloaded 0, added 1, done
 ELIFECYCLE  Command failed.
```

I use `"eslint": "^8.42.0"`.

**Comment by StanLaurent** [comment]
I don't think the package is still public

**Comment by garvae** [comment]
> ```shell
> > pnpm install @garvae/eslint-plugin-comments --save-dev
> 
> Packages: +1
> +
> node_modules/.pnpm/@garvae+eslint-plugin-comments@1.0.5_eslint@8.42.0/node_modules/@garvae/eslint-plugin-comments: Running postinstall script...
> Progress: resolved 700, reused 679, downloaded 0, added 1, done
>  ELIFECYCLE  Command failed.
> ```
> 
> I use `"eslint": "^8.42.0"`.

https://github.com/garvae/eslint-plugin-comments/issues/2#issuecomment-1773094227
